#!/bin/bash

#####################
# Build documentation.
#####################

if [ ! -f contrib/utilities/build_docs.sh ]; then
  echo "*** This script must be run from the top-level directory."
  exit 1
fi

source contrib/utilities/build_docs.sh

#
# Run sanity checks:
#
build_documentation